version: '3.7'

# ---
# This docker-compose  automates a set of operations on the Gravitee Bot GPG KEy Pair.
# Those operations are meant to test stanadrd operations on those Keys, in
# Pipelines, using two different formats :
#
# => binary format
# => base64 encoded text format
# ---
# Each container is based on the
# => cccc
# ---
# networks:
  # gpg_worker_net:
    # name: gpg_worker_net
volumes:
  gpg:
  signedfile:

services:
  # ---
  # In this container, I will import the
  # binary form GPG Key, export them as base64 encoded text files, and store them back
  gpg_worker_exporter:
    image: ${OCI_REPOSITORY_ORG}/${OCI_REPOSITORY_NAME}:${DESIRED_DOCKER_TAG}
    container_name: gpg_worker_exporter
    # ports:
      # # only expose https to outside world
      # - "443:443"   # SSL
    # command: /graviteeio/build.sh
    command: /bin/bash
    stdin_open: true
    tty: true
    # volumes:
      # - "$PWD/oci/runtime/frontend/webapp_src_code:/graviteeio/src_code"
    volumes:
      - "${HOME}/.secrethub/credential:/home/${NON_ROOT_USER_NAME}/.secrethub/credential"
      - gpg:/home/${NON_ROOT_USER_NAME}/.exported.secrets/.gpg/
      # - "$PWD/content/cicd-cheatsheet/circle-docker/assets/circleci-and-gpg/script:/home/${NON_ROOT_USER_NAME}/scripts"
    environment:
      - SECRETHUB_ORG=graviteeio
      - SECRETHUB_REPO=cicd
    labels:
      - "graviteeio.rocks=true"
    # depends_on:
      # - gpg_worker_backend
    # networks:
      # gpg_worker_net:
        # aliases:
          # - web.graviteeio.io

  # ---
  # In this container, I will import the
  # base 64 text form GPG Key, and sign a test file named ['armored.signed.test.file']
  gpg_worker_armor_signer:
    image: ${OCI_REPOSITORY_ORG}/${OCI_REPOSITORY_NAME}:${DESIRED_DOCKER_TAG}
    container_name: gpg_worker_armor_signer
    # ports:
      # # only expose https to outside world
      # - "443:443"   # SSL
    # command: /graviteeio/build.sh
    command: /bin/bash
    stdin_open: true
    tty: true
    # volumes:
      # - "$PWD/oci/runtime/frontend/webapp_src_code:/graviteeio/src_code"
    volumes:
      - "${HOME}/.secrethub/credential:/home/${NON_ROOT_USER_NAME}/.secrethub/credential"
      # - gpg:/home/${NON_ROOT_USER_NAME}/.exported.secrets/.gpg/
      - signedfile:/home/${NON_ROOT_USER_NAME}/.signed.files/

      # - "$PWD/content/cicd-cheatsheet/circle-docker/assets/circleci-and-gpg/script:/home/${NON_ROOT_USER_NAME}/scripts"
    environment:
      - SECRETHUB_ORG=graviteeio
      - SECRETHUB_REPO=cicd
    labels:
      - "graviteeio.rocks=true"
    # depends_on:
      # - gpg_worker_backend
    # networks:
      # gpg_worker_net:
        # aliases:
          # - web.graviteeio.io

# ------------
