version: '3.7'

# ---
# This docker-compose  automates a set of operations on the Gravitee Bot GPG KEy Pair.
# Those operations are meant to test stanadrd operations on those Keys, in
# Pipelines, using two different formats :
#
# => binary format
# => base64 encoded text format
# ---
# Each container is based on the
# => cccc
# ---
# networks:
  # gpg_worker_build_net:
    # name: gpg_worker_build_net

services:
  # ---
  # In this container, I will import the
  # binary form GPG Key, export them as base64 encoded text files, and store them back
  gpg_worker_exporter:
    image: ${OCI_REPOSITORY_ORG}/${OCI_REPOSITORY_NAME}:${DESIRED_DOCKER_TAG}
    container_name: gpg_worker_exporter
    # ports:
      # # only expose https to outside world
      # - "443:443"   # SSL
    # command: /graviteeio/build.sh
    command: /bin/bash
    stdin_open: true
    tty: true
    # volumes:
      # - "$PWD/oci/runtime/frontend/webapp_src_code:/graviteeio/src_code"
    volumes:
      - "${HOME}/.secrethub/credential:/home/${NON_ROOT_USER_NAME}/.secrehub/credential"
    labels:
      - "graviteeio.rocks=true"
    # depends_on:
      # - gpg_worker_backend
    # networks:
      # gpg_worker_build_net:
        # aliases:
          # - web.graviteeio.io

  # ---
  # In this container, I will import the
  # binary form GPG Key, and sign a test file named ['binary.signed.test.file']
  gpg_worker_binary_signer:
    image: ${OCI_REPOSITORY_ORG}/${OCI_REPOSITORY_NAME}:${DESIRED_DOCKER_TAG}
    container_name: gpg_worker_exporter
    # ports:
      # # only expose https to outside world
      # - "443:443"   # SSL
    # command: /graviteeio/build.sh
    command: /bin/bash
    stdin_open: true
    tty: true
    # volumes:
      # - "$PWD/oci/runtime/frontend/webapp_src_code:/graviteeio/src_code"
    volumes:
      - "${HOME}/.secrethub/credential:/home/${NON_ROOT_USER_NAME}/.secrehub/credential"
    labels:
      - "graviteeio.rocks=true"
    # depends_on:
      # - gpg_worker_backend
    # networks:
      # gpg_worker_build_net:
        # aliases:
          # - web.graviteeio.io
  # ---
  # In this container, I will import the
  # base 64 text form GPG Key, and sign a test file named ['armored.signed.test.file']
  gpg_worker_armor_signer:
    image: ${OCI_REPOSITORY_ORG}/${OCI_REPOSITORY_NAME}:${DESIRED_DOCKER_TAG}
    container_name: gpg_worker_exporter
    # ports:
      # # only expose https to outside world
      # - "443:443"   # SSL
    # command: /graviteeio/build.sh
    command: /bin/bash
    stdin_open: true
    tty: true
    # volumes:
      # - "$PWD/oci/runtime/frontend/webapp_src_code:/graviteeio/src_code"
    volumes:
      - "${HOME}/.secrethub/credential:/home/${NON_ROOT_USER_NAME}/.secrehub/credential"
    labels:
      - "graviteeio.rocks=true"
    # depends_on:
      # - gpg_worker_backend
    # networks:
      # gpg_worker_build_net:
        # aliases:
          # - web.graviteeio.io

  # ---
  # In this container, I will verify what Happens If I import the
  # binary form GPG Key, and verify the ['armored.signed.test.file'] signed file
  gpg_worker_armor_verifier:
    image: ${OCI_REPOSITORY_ORG}/${OCI_REPOSITORY_NAME}:${DESIRED_DOCKER_TAG}
    container_name: gpg_worker_exporter
    # ports:
      # # only expose https to outside world
      # - "443:443"   # SSL
    # command: /graviteeio/build.sh
    command: /bin/bash
    stdin_open: true
    tty: true
    # volumes:
      # - "$PWD/oci/runtime/frontend/webapp_src_code:/graviteeio/src_code"
    volumes:
      - "${HOME}/.secrethub/credential:/home/${NON_ROOT_USER_NAME}/.secrehub/credential"
    labels:
      - "graviteeio.rocks=true"
    # depends_on:
      # - gpg_worker_backend
    # networks:
      # gpg_worker_build_net:
        # aliases:
          # - web.graviteeio.io

  # ---
  # In this container, I will verify what Happens If I import the
  # base 64 encoded text form GPG Key, and verify the ['binary.signed.test.file'] signed file
  gpg_worker_binary_verifier:
    image: ${OCI_REPOSITORY_ORG}/${OCI_REPOSITORY_NAME}:${DESIRED_DOCKER_TAG}
    container_name: gpg_worker_exporter
    # ports:
      # # only expose https to outside world
      # - "443:443"   # SSL
    # command: /graviteeio/build.sh
    command: /bin/bash
    stdin_open: true
    tty: true
    # volumes:
      # - "$PWD/oci/runtime/frontend/webapp_src_code:/graviteeio/src_code"
    volumes:
      - "${HOME}/.secrethub/credential:/home/${NON_ROOT_USER_NAME}/.secrehub/credential"
    labels:
      - "graviteeio.rocks=true"
    # depends_on:
      # - gpg_worker_backend
    # networks:
      # gpg_worker_build_net:
        # aliases:
          # - web.graviteeio.io

# ------------
