version: '3.7'

# ---
# This docker-compose  automates a set of operations on the Gravitee Bot GPG KEy Pair.
# Those operations are meant to test stanadrd operations on those Keys, in
# Pipelines, using two different formats :
#
# => binary format
# => base64 encoded text format
# ---
# Each container is based on the
# => cccc
# ---
# networks:
  # gpg_worker_build_net:
    # name: gpg_worker_build_net

services:
  # ---
  # This service builds the base image for all of the services defined in :
  # => docker-compose.final.yml
  # => docker-compose.yml
  # ---
  gpg_worker_builder:
    image: ${OCI_REPOSITORY_ORG}/${OCI_REPOSITORY_NAME}:${DESIRED_DOCKER_TAG}
    # command: --api --docker
    container_name: gpg_worker_exporter
    build:
      context: ./oci
      args:
        - MAVEN_VERSION=${MAVEN_VERSION}
        - OPENJDK_VERSION=${OPENJDK_VERSION}
        - OCI_VENDOR=${OCI_VENDOR}
        - NON_ROOT_USER_UID=${NON_ROOT_USER_UID}
        - NON_ROOT_USER_GID=${NON_ROOT_USER_GID}
        - NON_ROOT_USER_NAME=${NON_ROOT_USER_NAME}
        - NON_ROOT_USER_GRP=${NON_ROOT_USER_GRP}
    # ports:
      # # only expose https to outside world
      # - "443:443"   # SSL
    # command: /graviteeio/build.sh
    command: /bin/bash
    stdin_open: true
    tty: true
    # volumes:
      # - "$PWD/oci/runtime/frontend/webapp_src_code:/graviteeio/src_code"
    labels:
      - "graviteeio.rocks=true"
