baseURL = "http://127.0.0.1:1313/"
languageCode = "en-us"
title = "Gravitee.io API Platform"
themesDir = "themes"
theme = "gravitee-docs"

# [menu]

  # [[menu.mainmenu]]
    # identifier = "mainmenu"
    # name = "Main menu"
    # pre = "<i class='fa fa-heart'></i>"
    # url = "/"
    # weight = -110

  # [[menu.developer_guide]]
    # identifier = "developer_guide"
    # name = "Developer Guide"
    # post = "<span class='alert'>New!</span>"
    # pre = "<i class='fa fa-road'></i>"
    # url = "/developer-guide/"
    # weight = -100

  # [[menu.tutorials]]
    # identifier = "tutorials"
    # name = "Tutorials"
    # post = "<span class='alert'>New!</span>"
    # pre = "<i class='fa fa-road'></i>"
    # url = "/tutorials/"
    # weight = -100

[menu]
  # ---
  # There is one menu called "Concepts and Design" in the top navbar menu
  # -
  # Associated hugo content types :
  #   - concepts
  #   - concepts
  # ---
  [[menu.concepts]]
    identifier = "general_design"
    name = "General Design"
    url = "/concepts/general-design/"
    weight = 0

  [[menu.concepts]]
    identifier = "circleci_pipelines"
    name = "Circle CI Pipelines"
    url = "/concepts/circleci-pipelines/"
    weight = 10

  [[menu.concepts]]
    identifier = "circleci_orbs"
    name = "Circle CI Orbs"
    url = "/concepts/circleci-orbs/"
    weight = 20

  [[menu.concepts]]
    identifier = "cicd_infra"
    name = "Ci Cd System's Infrastructure"
    url = "/concepts/cicd-infra/"
    weight = 30

  [[menu.concepts]]
    identifier = "devops_gitops_cicd"
    name = "Higher Order Ci Cd for Devops"
    url = "/concepts/devops-gitops-cicd/"
    weight = 40

  # ---
  # There is one menu called "CI/CD Processes" in the top navbar menu
  # -
  # Associated hugo content types :
  #   - cicd-processes
  #   - apim-processes
  #   - am-processes
  #   - ae-processes
  #   - cockpit-processes
  # ---
  [[menu.cicd_processes]]
    identifier = "apim_processes"
    name = "Gravitee APIM"
    url = "/cicd-processes/apim/"
    weight = 50
  [[menu.cicd_processes]]
    identifier = "am_processes"
    name = "Gravitee AM"
    url = "/cicd-processes/am/"
    weight = 60
  [[menu.cicd_processes]]
    identifier = "ae_processes"
    name = "Gravitee AE"
    url = "/cicd-processes/ae/"
    weight = 70
  [[menu.cicd_processes]]
    identifier = "cockpit_processes"
    name = "Gravitee Cockpit"
    url = "/cicd-processes/cockpit/"
    weight = 80
  # ---
  # There is one menu called "CI/CD Standard Operations" in the top navbar menu
  # ---
  [[menu.standard_operations]]
    identifier = "developer_guide"
    name = "Developer Guide"
    url = "/standard-operations/developer-guide/"
    weight = 90

  [[menu.standard_operations]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "/standard-operations/tutorials/"
    weight = 100

  # ---
  # There is one menu called "Secrets Management" in the top navbar menu
  # ---
  [[menu.secrets_management]]
    identifier = "Secrethub"
    name = "The Secrethub: User Guide"
    url = "/secrets-management/secrethub-guide/"
    weight = 110

  [[menu.secrets_management]]
    identifier = "taxonomy_tree"
    name = "Secrets Inventory: The Secrets Taxonomy Tree"
    url = "/secrets-management/secrets-inventory/"
    weight = 120

  [[menu.secrets_management]]
    identifier = "initialization"
    name = "Secrets Initialization"
    url = "/secrets-management/secrets-initialization/"
    weight = 130

  [[menu.secrets_management]]
    identifier = "rotation"
    name = "Secrets Rotation"
    url = "/secrets-management/secrets-rotation/"
    weight = 140


  # ---
  # There is one menu called "On Github" in the top navbar menu
  # -
  # Associated hugo content type : on-github
  # ---
  [[menu.on_github]]
    identifier = "github_orchestrator"
    name = "The Orchestrator on Github"
    url = "/on_github/orchestrator/"
    weight = 150
  [[menu.on_github]]
    identifier = "github_orbs"
    name = "The Gravitee Orbs on Github"
    url = "/on_github/circleci-orbs/"
    weight = 160
  [[menu.on_github]]
    identifier = "github_dev_repos"
    name = "The Gravitee Orbs on Github"
    url = "/on_github/dev-repos/"
    weight = 150

  # ---
  # There is one menu called "Devops" in the top navbar menu
  # -
  # Associated hugo content types :
  #   - general-practices
  #   - cockpit-saas
  # ---
  [[menu.devops]]
    identifier = "general_practices"
    name = "General Practices"
    url = "/devops/general-practices/"
    weight = 155

  [[menu.devops]]
    identifier = "cockpit_saas"
    name = "Cockpit Saas"
    url = "/devops/cockpit-saas/"
    weight = 160

  [[menu.cicd_cheatsheet]]
    identifier = "circle_docker"
    name = "Circle CI and Docker"
    url = "/cicd-cheatsheet/circle-docker/"
    weight = 170
