# circleci/python:buster
version: 2.1

parameters:
  gio_action:
    type: enum
    enum: [apim_forensics, blank]
    default: blank
  nightly_snapshot_version:
    type: string
    default: $NIGHTLY_SNAPSHOT_VERSION
    description: "What is the SNAPSHOT version of APIM nightly to forensics-analyse ?"

orbs:
  gravitee: gravitee-io/gravitee@dev:1.0.4
  secrethub: secrethub/cli@1.1.0

# --- Jobs to perform all workflows
# jobs:


workflows:
  version: 2.1
  # -- typically this workflow is executed on pull requests events for Community Edition Gravitee Repositories
  apim_forensics:
    when:
      and:
        - equal: [ apim_forensics, << pipeline.parameters.gio_action >> ]
    jobs:
      - gravitee/d_apim_forensics_secrets:
          context: cicd-orchestrator
          name: apim_forensics_resolution
      - gravitee/d_apim_nightly_forensics:
          name: apim_forensics_analysis
          requires:
            - apim_forensics_resolution
          nightly_snapshot_version: << pipeline.parameters.nightly_snapshot_version >>
          # nexus_snapshots_url: 'https://oss.sonatype.org/content/repositories/snapshots'
          # nexus_snapshots_server_id: 'sonatype-nexus-snapshots'
          # container_gun_image_org: 'circleci'
          # container_gun_image_name: 'openjdk'
          # container_gun_image_tag: '11.0.3-jdk-stretch'
          container_size: 'xlarge'
          # filters:
            # branches:
              # ignore:
                # - master
                # - /^[0-999].[0-999].x/ # Ignore support branches, because they are checked with nightly ? Would make sense...
  # --
  # the blank workflow is on pupose filtered on all git branches
  blank:
    when:
      and:
        - equal: [ blank, << pipeline.parameters.gio_action >> ]
    jobs:
      - gravitee/d_apim_nightly_forensics:
          name: apim_forensics_analysis
          requires:
            - apim_forensics_resolution
          container_size: 'small'
          filters:
            branches:
              ignore:
                - master
                - /^*/ # filter all branches
                # - /^[0-999].[0-999].x/ # Ignore support branches, because they are checked with nightly ? Would make sense...
